# Site settings
title: "keiz44l"
bye_message: "Thx!"
baseurl: "/"
url: "/"
disqus: keiz44l

# Header settings
nick: "keiz44l"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "keiz44l"
blog:
    server: "wordpress.com"
    nick: "keiz44l"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
